---
- name: Create monitoring server certs
  hosts: monitoring_host
  become: true
  gather_facts: true
  roles:
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.ssl_certificates
      vars:
        ssl_certificate: "{{ monitoring_server_ssl_certificate }}"

- name: Install Monitoring Service
  ansible.builtin.import_playbook: mirsg.infrastructure.install_monitoring
