---
- name: Setup for the firewall
  hosts: all
  gather_facts: true
  tasks:
    - name: Update YUM repo baseurls
      ansible.builtin.include_role:
        name: mirsg.infrastructure.provision
        tasks_from: RedHat7.yml
      when: ansible_facts['distribution_major_version'] is version('7')

    - name:
        Set skip_if_unavailable to avoid failures from retired PGDG EL7 repos
      community.general.ini_file:
        path: /etc/yum.conf
        section: main
        option: skip_if_unavailable
        value: "1"
        mode: "0644"
      when: ansible_facts['distribution_major_version'] is version('7')

    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Change firewalld backend to iptables
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: ^FirewallBackend=
        line: FirewallBackend=iptables
