---
- name: Ensure correct Java version is installed - {{ java_package }}
  ansible.builtin.package:
    name: "{{ java_package }}-{{ java_package_version }}"
    state: installed

- name: Set JAVA_HOME through shell script
  ansible.builtin.template:
    src: java_home.sh.j2
    dest: "{{ java_profile_d }}/java_home.sh"
    mode: "0644"
  when: java_home is defined and java_home != ''

- name: Get info for java package directory
  ansible.builtin.stat:
    path: /usr/lib/jvm/{{ java_package }}
  register: java_package_info

- name: Check if JRE exists
  ansible.builtin.stat:
    path: "{{ java_package_info.stat.lnk_source }}/jre"
  register: java_jre

- name: Set the default java version - {{ java_package_info.stat.lnk_source }}
  community.general.alternatives:
    name: java
    path: "{{ java_package_info.stat.lnk_source }}/jre/bin/java"
    state: selected
  when: java_jre.stat.exists

- name: Set the default java version - {{ java_package_info.stat.lnk_source }}
  community.general.alternatives:
    name: java
    path: "{{ java_package_info.stat.lnk_source }}/bin/java"
    state: selected
  when: not java_jre.stat.exists
