---
- name: Verify nginx configured as a reverse proxy
  hosts: localhost
  tasks:
    - name: Get server status
      ansible.builtin.uri:
        url: https://localhost:8080
        method: GET
        headers:
          Host: molecule.instance.local
        validate_certs: false
        return_content: true
      register: response

    - name: Check server status and response
      ansible.builtin.assert:
        that:
          - response.status == 200
          - response.server == "nginx"
          - response.content is search('Hello World!')
