---
- name: Setup for firewalld role
  hosts: all
  gather_facts: true
  tasks:
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Change firewalld backend to iptables
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: "^FirewallBackend="
        line: FirewallBackend=iptables
