---
- name: Setup for firewalld role
  hosts: all
  gather_facts: true
  tasks:
    - name: Update YUM repo baseurls
      ansible.builtin.include_role:
        name: mirsg.infrastructure.provision
        tasks_from: CentOS.yml
      when:
        ansible_facts['os_family'] == "RedHat" and
        ansible_facts['distribution_major_version'] is version('7')

    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Change firewalld backend to iptables
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: ^FirewallBackend=
        line: FirewallBackend=iptables
