---
- name: Ensure Docker certificate directory exists on the client
  ansible.builtin.file:
    path: "{{ xnat_container_service_certificate_directory }}"
    state: directory
    owner: "{{ xnat_container_service_owner }}"
    group: "{{ xnat_container_service_group }}"
    mode: "0700"

- name: Copy Docker server certificate from Ansible Controller cache to client
  ansible.builtin.copy:
    src: "{{ xnat_container_service_certificate_cache_directory }}/ca.pem"
    dest: "{{ xnat_container_service_server_ca_cert }}"
    owner: "{{ xnat_container_service_owner }}"
    group: "{{ xnat_container_service_group }}"
    mode: "0600"

- name:
    Copy signed Docker client certificate from Ansible Controller cache to
    client
  ansible.builtin.copy:
    src:
      "{{ xnat_container_service_certificate_cache_directory }}/{{
      xnat_container_service_client_hostname }}.cert"
    dest: "{{ xnat_container_service_cert }}"
    owner: "{{ xnat_container_service_owner }}"
    group: "{{ xnat_container_service_group }}"
    mode: "0600"

- name: Copy private key from Ansible Controller cache to client
  ansible.builtin.copy:
    src: "{{ xnat_container_service_certificate_cache_directory }}/key.pem"
    dest: "{{ xnat_container_service_key }}"
    owner: "{{ xnat_container_service_owner }}"
    group: "{{ xnat_container_service_group }}"
    mode: "0600"

- name: Configure XNAT to talk to container service
  ansible.builtin.uri:
    url: "{{ xnat_container_service_url }}"
    user: "{{ xnat_service_admin.username }}"
    password: "{{ xnat_service_admin.password }}"
    method: POST
    body_format: json
    body:
      name: "{{ xnat_container_service_name }}"
      host:
        https://{{ xnat_container_service_hostname }}:{{
        xnat_container_service_port }}
      cert-path: "{{ xnat_container_service_certificate_directory }}"
      swarm-mode: false
      path-translation-xnat-prefix:
        "{{ xnat_container_service_path_translation_xnat_prefix }}"
      path-translation-docker-prefix:
        "{{ xnat_container_service_path_translation_docker_prefix }}"
      pull-images-on-xnat-init: false
      container-user: ""
    validate_certs: "{{ xnat_container_service_validate_certs }}"
    status_code: 200, 201
