---
- name: Prepare - install sudo
  hosts: all
  gather_facts: true
  tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

- name: Prepare - install and start crontabs on the db
  hosts: db
  become: true
  gather_facts: true
  tasks:
    - name: Install crontabs
      ansible.builtin.yum:
        name: cronie
        state: present
    - name: Start crontabs service
      ansible.builtin.service:
        name: crond.service
        state: started
        enabled: true
    - name: Import postgresql RPM GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://apt.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL

- name: Create SSL certs for tests
  hosts: omero
  gather_facts: true
  roles:
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.ssl_certificates

- name: Prepare firewalld
  hosts: all
  gather_facts: true
  tasks:
    - name: Install and configure firewalld
      block:
        - name: Install firewalld
          ansible.builtin.package:
            name: firewalld
            state: present

        - name: Change firewalld backend to iptables
          ansible.builtin.lineinfile:
            path: /etc/firewalld/firewalld.conf
            regexp: "^FirewallBackend="
            line: FirewallBackend=iptables
