---
- name: Ensure os baseurl is present in repository file
  ansible.builtin.yum_repository:
    name: base
    description: CentOS-$releasever - Base
    file: CentOS-Base
    baseurl: "{{ provision_yum_repo_base_baseurl }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: true
    state: present

- name: Ensure updates baseurl is present in repository file
  ansible.builtin.yum_repository:
    name: updates
    description: CentOS-$releasever - Updates
    file: CentOS-Base
    baseurl: "{{ provision_yum_repo_updates_baseurl }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: true
    state: present

- name: Ensure extras baseurl is present in repository file
  ansible.builtin.yum_repository:
    name: extras
    description: CentOS-$releasever - Extras
    file: CentOS-Base
    baseurl: "{{ provision_yum_repo_extras_baseurl }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present

- name: Ensure centosplus baseurl is present in repository file
  ansible.builtin.yum_repository:
    name: centosplus
    description: CentOS-$releasever - Plus
    file: CentOS-Base
    baseurl: "{{ provision_yum_repo_centosplus_baseurl }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: false
    state: present

- name: Check if locale already set
  ansible.builtin.shell: |
    set -o pipefail
    localectl status | grep -i {{ server_locale | quote }}
  register: found_locale
  changed_when: false
  failed_when: false

- name: Install and set locale
  when: found_locale.rc != 0
  block:
    - name: Allow install of other locales
      ansible.builtin.lineinfile:
        path: /etc/yum.conf
        search_string: override_install_langs=en_US.utf8
        state: absent

    - name: Install locales # noqa: package-latest
      ansible.builtin.yum:
        name: glibc-common
        state: latest

    - name: Set locale
      ansible.builtin.command:
        localectl set-locale LANG={{ server_locale | quote }}
      changed_when: false
