---
- name: Install the ca-certificates package
  become: true
  ansible.builtin.yum:
    name: "ca-certificates"
    state: present

- name: Disable default Postgres module # noqa command-instead-of-module
  ansible.builtin.command: yum module disable -y postgresql
  register: disable_postgresql_module
  changed_when:
    - "'Disabling modules:' in disable_postgresql_module.stdout"

- name: Import postgresql rpm key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ postgresql_rpm_gpg_key_pgdg }}"

- name: Check if locale already set
  ansible.builtin.shell: |
    set -o pipefail
    localectl status | grep -i {{ server_locale | quote }}
  register: found_locale
  changed_when: false
  failed_when: false

- name: Install and set locale
  when: found_locale.rc != 0
  block:
    - name: Install locale
      ansible.builtin.yum:
        name: glibc-langpack-en
        state: present

    - name: Set locale
      ansible.builtin.command: "localectl set-locale LANG={{ server_locale | quote }}"
      changed_when: false
