---
collections:
  - name: community.general
    version: 11.4.1
  - name: ansible.posix
  - name: community.postgresql
  - name: community.docker
    version: 4.8.4
  - name: community.crypto
    version: ">=2.14.1,<3.0.0"
