---
collections:
  - community.general
  - ansible.posix
  - community.postgresql
  - community.docker
  - community.crypto

roles:
  - src: ome.omero_web
    version: 5.1.1

  - src: ome.omero_user
    version: 0.3.1

  # required for omero_web 4.0.1
  - src: ome.selinux_utils
    version: 2.0.2

  - src: ome.omero_common
    version: 0.4.0

  - src: ome.python3_virtualenv
    version: 0.2.0

  - src: ome.ice
    version: 4.3.0
