---
nginx_owner: root
nginx_group: root

nginx_log_folder: /var/log/nginx
nginx_access_log: "{{ nginx_log_folder }}/access.log"
nginx_error_log: "{{ nginx_log_folder }}/error.log"
nginx_app_access_log: "{{ nginx_log_folder }}/app.access.log"
nginx_app_error_log: "{{ nginx_log_folder }}/app.error.log"

nginx_http_port: 80
nginx_https_port: 443

nginx_conf_template: nginx_reverse_proxy.j2 # check the template file for the variables it requires
nginx_conf_file: /etc/nginx/nginx.conf
nginx_add_default_server: true

nginx_ipv6_enabled: false

nginx_use_ssl: true
nginx_certs_dir: /etc/nginx/ssl
nginx_ssl_cert_file: /etc/nginx/ssl/server.cert
nginx_ssl_key_file: /etc/nginx/ssl/server.key

# Bit size for OpenSSL Diffie-Hellman Parameters. Higher bit sizes are more
# secure, but require exponentially larger times for the one-off parameter
# generation. Use 4096 for production. These may take 10mins+ to generate but
# are only generated once per server.
# For local testing (non-production), use 2048 to speed up deployment.
nginx_diffie_helman_size_bits: 4096
nginx_dh_params_file: /etc/nginx/ssl/dhparam.pem
