---
xnat_version: 1.9.0
xnat_pipeline_version: 1.8.10
xnat_archive_dir: "{{ xnat_root_dir }}/archive"
xnat_prearchive_dir: "{{ xnat_root_dir }}/prearchive"
xnat_cache_dir: "{{ xnat_root_dir }}/cache"
xnat_build_dir: "{{ xnat_root_dir }}/build"
xnat_ftp_dir: "{{ xnat_root_dir }}/ftp"
xnat_pipeline_dir: "{{ xnat_root_dir }}/pipeline"
xnat_inbox_dir: "{{ xnat_root_dir }}/inbox"
xnat_plugins_dir: "{{ xnat_home_dir }}/plugins"
xnat_config_dir: "{{ xnat_home_dir }}/config"
xnat_logs_dir: "{{ xnat_home_dir }}/logs"
xnat_work_dir: "{{ xnat_home_dir }}/work"
xnat_create_data_directory: true
xnat_link_data_directory: true

# Mail server settings
xnat_smtp_enabled: false
xnat_smtp_hostname: ""
xnat_smtp_port: 2525
xnat_smtp_protocol: smtp
xnat_smtp_auth: ""
xnat_smtp_username: ""
xnat_smtp_password: "{{ vault_smtp_password | default(omit) }}"
xnat_smtp_start_tls: false
xnat_smtp_ssl_trust: "*"

# LDAP configuration
xnat_ldap_enabled: false
xnat_ldap_name: ""
xnat_ldap_address: ""
xnat_ldap_userdn: ""
xnat_ldap_password: "{{ vault_ldap_password | default(omit) }}"
xnat_ldap_base: ""
xnat_ldap_filter: ""
xnat_ldap_ca_cert: ""
xnat_ldap_keystore_alias: ""

# Plugins
xnat_plugin_urls:
  - https://api.bitbucket.org/2.0/repositories/xnatdev/container-service/downloads/container-service-3.6.0-fat.jar
  - https://api.bitbucket.org/2.0/repositories/xnatx/xnatx-batch-launch-plugin/downloads/batch-launch-0.7.0.jar

xnat_plugin_bundle_urls: [] # yamllint disable-line rule:brackets
xnat_plugin_packages: [] # yamllint disable-line rule:brackets
xnat_server_specific_plugin_urls: [] # yamllint disable-line rule:brackets
xnat_server_specific_plugin_packages: [] # yamllint disable-line rule:brackets

# Path to server logo file
xnat_config_logo: /images/logo.png # use the default XNAT logo

# Pipeline engine
xnat_pipeline_engine_enabled: false

# Note that AutoRun is currently required for session archive notifications
xnat_autorun_enabled: false
