---
ansible_cache_dir: "{{ lookup('env', 'HOME') }}/ansible_persistent_files"

external_storage_drive: "/storage/molecule"
selinux_enabled: false

# mirsg.infrastructure.provision
server_locale: "en_GB.UTF-8"
