---
# mirsg.infrastructure.install_python
install_python:
  version: "2"
  pip_version: "20.3.4"
  pip_executable: "pip"
  system_packages:
    - python
    - python-pip
    - python-setuptools
  pip_packages:
    - cryptography
