---
monitoring_server_hostname: "{{ hostvars['mserv']['hostname'] }}"
monitoring_server_ssl_cert: "/etc/ssl/certs/{{ monitoring_server_hostname }}.cert"
monitoring_server_ssl_key: "/etc/ssl/certs/{{ monitoring_server_hostname }}.key"
monitoring_server_admin_username: mirsg_service
monitoring_server_admin_password: password
monitoring_server_admin_email: admin@monitoring.org
monitoring_server_notification_email: test@monitoring.org
monitoring_server_storage_root: "{{ external_storage_drive }}/monitoring"
monitoring_server_owner: monitoring
monitoring_server_group: monitoring
monitoring_server_uid: 595
monitoring_server_gid: 595
monitoring_server_validate_certs: false
monitoring_server_cert_owner: root
monitoring_server_cert_group: root
monitoring_server_cert_dir: /root/monitoring_certs
monitoring_server_client_cert_dir: /root/monitoring_certs/client_certs
monitoring_server_hostname_extractor: "hostname"
monitoring_server_grafana_username: grafana
monitoring_server_grafana_password: grafana
monitoring_server_grafana_host: "{{ monitoring_server_hostname }}"
