---
- name: Ensure monitoring server cert dir exists
  ansible.builtin.file:
    path: "{{ monitoring_server_certificate_directory }}"
    state: directory
    owner: "{{ monitoring_server_cert_owner }}"
    group: "{{ monitoring_server_cert_group }}"
    mode: "0700"

- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ monitoring_server_ca_key }}"
    owner: "{{ monitoring_server_cert_owner }}"
    group: "{{ monitoring_server_cert_group }}"
    mode: "0400"

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ monitoring_server_ca_csr }}"
    privatekey_path: "{{ monitoring_server_ca_key }}"
    common_name: "{{ monitoring_server_hostname }}"
    subject_alt_name: "IP:{{ monitoring_server_ip }}"
    basic_constraints_critical: true
    basic_constraints: ["CA:TRUE"]

- name: Generate self-signed CA certificate
  community.crypto.x509_certificate:
    path: "{{ monitoring_server_ca_cert }}"
    privatekey_path: "{{ monitoring_server_ca_key }}"
    csr_path: "{{ monitoring_server_ca_csr }}"
    provider: selfsigned
    owner: "{{ monitoring_server_cert_owner }}"
    group: "{{ monitoring_server_cert_owner }}"
    mode: "0400"
