---
- name: Start cadvisor container
  community.docker.docker_container:
    name: "{{ monitoring_server_cadvisor.container_name }}"
    hostname: "{{ monitoring_server_cadvisor.container_name }}"
    image: "{{ monitoring_server_cadvisor.image }}"
    state: started
    user: "{{ monitoring_server_uid }}:{{ monitoring_server_gid }}"
    networks:
      - name: monitor-net
    command:
      - "-url_base_prefix=/cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    restart_policy: always
