---
# mirsg.infrastructure.docker
docker_generate_certificates: true # generate TLS certs for clients
docker_client_hostnames:
  - "{{ hostvars['xnat_web']['hostname'] }}"
docker_tls_verify: false

# mirsg.infrastructure.firewalld
firewalld_internal_zone_sources:
  - "{{ web_server.subnet | default(web_server.ip + '/32') }}"

firewalld_internal_zone_ports:
  - "{{ docker_server_port }}"
