---
# mirsg.infrastructure.install_python
install_python:
  version: "3"
  pip_version: "21.3.1"
  pip_executable: "/usr/local/bin/pip3"
  system_packages:
    - python3
    - python3-pip
    - python3-setuptools
  pip_packages:
    - cryptography
