---
all:
  # List of all servers, defining their alias and IP (hostname)
  hosts:
    # Host for your database server.
    omero_db:
      hostname: omero.db.local
      ansible_ip: 192.168.56.2
    # Host for your web server.
    omero_server_web:
      hostname: omero.server.local
      ansible_ip: 192.168.56.3

  # Ansible groups. Groups allow configuration and variables to be shared between hosts
  # Variables in group_vars/all will be shared between all hosts
  children:
    # All PostgreSQL servers. Variables in group_vars/db will be shared between these hosts
    db:
      hosts:
        omero_db:

    # All the omero servers (OMERO.server + OMERO.web).
    # Variables in group_vars/omero will be shared between these hosts
    omero:
      hosts:
        omero_server_web:
