---
- name: Ensure monitoring cert dir exists on client
  ansible.builtin.file:
    path: "{{ monitoring_client_cert_dir }}"
    state: directory
    owner: "{{ monitoring_client_owner }}"
    group: "{{ monitoring_client_group }}"
    mode: "0700"

- name: Copy monitoring server certificate to client
  ansible.builtin.copy:
    src: "{{ monitoring_client_certificate_cache_directory }}/ca.pem"
    dest: "{{ monitoring_client_server_ca_cert_file }}"
    owner: "{{ monitoring_client_owner }}"
    group: "{{ monitoring_client_group }}"
    mode: "0600"

- name: Copy signed monitoring client certificate to client
  ansible.builtin.copy:
    src:
      "{{ monitoring_client_certificate_cache_directory }}/{{
      monitoring_client_certificate_file }}"
    dest: "{{ monitoring_client_ssl_cert_file }}"
    owner: "{{ monitoring_client_owner }}"
    group: "{{ monitoring_client_group }}"
    mode: "0600"

- name: Copy signed monitoring client key to client
  ansible.builtin.copy:
    src: "{{ monitoring_client_certificate_cache_directory }}/key.pem"
    dest: "{{ monitoring_client_ssl_key_file }}"
    owner: "{{ monitoring_client_owner }}"
    group: "{{ monitoring_client_group }}"
    mode: "0600"

- name: Install and configure Node exporter
  ansible.builtin.include_tasks: install_node_exporter.yml
