---
- name: Ensure monitoring cert dir exists on client
  ansible.builtin.file:
    path: "{{ monitoring_client.cert_dir }}"
    state: directory
    owner: "{{ monitoring_client.owner }}"
    group: "{{ monitoring_client.group }}"
    mode: "0700"

- name: Generate OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ monitoring_client.ssl_key_file }}"
    owner: "{{ monitoring_client.owner }}"
    group: "{{ monitoring_client.group }}"
    mode: "0400"
  register: new_monitoring_client_private_key_generated

- name: Generate OpenSSL CSR
  community.crypto.openssl_csr:
    path: "{{ monitoring_client.ssl_csr_file }}"
    privatekey_path: "{{ monitoring_client.ssl_key_file }}"
    common_name: "{{ ansible_host }}"
  register: new_monitoring_client_csr_generated

- name: Copy client CSR
  ansible.builtin.fetch:
    src: "{{ monitoring_client.ssl_csr_file }}"
    dest: "{{ monitoring_temp_files_cert_dir }}/{{ ansible_host }}.csr"
    flat: true
