---
- name: Install and configure Docker server
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: mirsg.infrastructure.docker

- name: Configure Docker client
  hosts: client
  become: true
  gather_facts: true
  tasks:
    - name: Ensure Docker certificate directory exists on the client
      ansible.builtin.file:
        path: /root/docker_certs
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Copy Docker server certificate from Ansible Controller cache to client
      ansible.builtin.copy:
        src: "{{ docker_client_certificate_cache_directory }}/ca.pem"
        dest: /root/docker_certs/ca.pem
        owner: root
        group: root
        mode: "0600"

    - name: Copy signed Docker client certificate from Ansible Controller cache to client
      ansible.builtin.copy:
        src: "{{ docker_client_certificate_cache_directory }}/molecule.docker-client.local.cert"
        dest: /root/docker_certs/cert.pem
        owner: root
        group: root
        mode: "0600"

    - name: Copy private key from Ansible Controller cache to client
      ansible.builtin.copy:
        src: "{{ docker_client_certificate_cache_directory }}/key.pem"
        dest: /root/docker_certs/key.pem
        owner: root
        group: root
        mode: "0600"
