---
- name: Check if Python 2 is the default version for the OS
  ansible.builtin.set_fact:
    default_python_version: "2"
  when: >-
    (ansible_os_family == 'RedHat') and (ansible_distribution_major_version |
    int < 8) or (ansible_distribution == 'Debian') and
    (ansible_distribution_major_version | int < 10) or (ansible_distribution ==
    'Ubuntu') and (ansible_distribution_major_version | int < 18)

- name: Check if Python 3 is the default version for the OS
  ansible.builtin.set_fact:
    default_python_version: "3"
  when: >-
    (ansible_os_family == 'RedHat') and (ansible_distribution_major_version |
    int >= 8) or (ansible_distribution == 'Debian') and
    (ansible_distribution_major_version | int >= 10) or (ansible_distribution ==
    'Ubuntu') and (ansible_distribution_major_version | int >= 18)

- name: Remove python3-requests
  ansible.builtin.package:
    name: python3-requests
    state: absent
  when: default_python_version == "3"

- name: Remove python-requests
  ansible.builtin.package:
    name: python-requests
    state: absent
  when: default_python_version == "2"
