---
- name: Install system packages required by OMERO.server
  ansible.builtin.package:
    name: "{{ omero_server_system_packages }}"
    state: present

- name: Install Ice
  ansible.builtin.include_tasks:
    file: ice.yml

- name: Ensure postgres RPM is installed
  ansible.builtin.package:
    name: "{{ postgresql_install.rpm }}"
    state: present
    disable_gpg_check: "{{ postgresql_install.disable_gpg_check }}"

- name: Ensure postgresql is installed
  ansible.builtin.package:
    name: "{{ postgresql_install.yum_client_package }}"
    state: installed

- name: Get postgres server certificate from cache
  ansible.builtin.copy:
    src: "{{ database_server_certificate_cache_filename }}"
    dest: "{{ postgresql_client.server_certificate_filename }}"
    owner: "{{ omero_server_system_user }}"
    group: "{{ omero_server_system_user }}"
    mode: "0600"
  when: postgresql_use_ssl
  notify: Restart omero-server

- name: Remove OMERO scripts
  ansible.builtin.file:
    path: "{{ omero_server_basedir }}/OMERO.server/lib/scripts/omero"
    state: absent
  notify: Restart omero-server
  tags:
    - molecule-idempotence-notest
