---
all:
  hosts:
    client:
      hostname: "molecule.docker-client.local"
      ansible_ip: "192.168.56.2"
    server:
      hostname: "molecule.docker-server.local"
      ansible_ip: "192.168.56.3"
