---
- name: Ensure correct Java version is installed - {{ java_package }}
  ansible.builtin.package:
    name: "{{ java_package }}"
    state: installed

- name: Set JAVA_HOME through shell script
  ansible.builtin.template:
    src: "java_home.sh.j2"
    dest: "{{ java_profile_d }}/java_home.sh"
    mode: "0644"
  when: java_home != ''

- name: Ensure Ansible seport dependencies are installed
  ansible.builtin.yum:
    name: ["libselinux-python", "policycoreutils-python"]
    state: installed
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] is version('7')

- name: Ensure Ansible seport dependencies are installed
  ansible.builtin.yum:
    name: ["python3-libselinux", "policycoreutils-python-utils"]
    state: installed
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] is version("8", ">=")

- name: Ensure epel is installed
  ansible.builtin.yum:
    name: "epel-release"
    state: installed

- name: Ensure Tomcat Native library is installed
  ansible.builtin.yum:
    name: "tomcat-native"
    state: installed

- name: Configure SELinux to allow Tomcat to listen on port {{ tomcat_port }}
  community.general.seport:
    ports: "{{ tomcat_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled

- name: Add tomcat group
  ansible.builtin.group:
    name: "{{ tomcat_group }}"

- name: Add "tomcat" user
  ansible.builtin.user:
    name: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    home: "{{ tomcat_catalina_home }}"
    createhome: false
    system: true

- name: Check for existing Tomcat install
  ansible.builtin.stat:
    path: "{{ tomcat_catalina_home }}/bin"
  register: tomcat_check

- name: Check installed Tomcat version
  ansible.builtin.shell: |
    set -o pipefail
    ./version.sh | grep -oP '(?<=Apache Tomcat/)([0-9]+\.?)+'
  args:
    chdir: "{{ tomcat_catalina_home }}/bin"
  register: tomcat_check_version
  when: "tomcat_check.stat.exists"
  changed_when: false
  failed_when: tomcat_check_version.stderr

- name: Upgrade/install Tomcat if needed
  ansible.builtin.include_tasks: tasks/upgrade.yml
  when: "not tomcat_check.stat.exists or tomcat_version not in tomcat_check_version.stdout"

- name: Copy tomcat service file
  ansible.builtin.template:
    src: templates/tomcat.service.j2
    dest: "{{ tomcat_service_config_file }}"
    mode: "0644"
  when: ansible_service_mgr == "systemd"

- name: Copy Tomcat config file
  ansible.builtin.template:
    src: tomcat.conf.j2
    dest: "{{ tomcat_config_file }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: "0644"
    force: true
  notify: Restart tomcat

- name: Start and enable tomcat
  ansible.builtin.service:
    daemon_reload: true
    name: tomcat
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"

- name: Copy Tomcat setenv.sh file
  ansible.builtin.template:
    src: setenv.sh.j2
    dest: "{{ tomcat_catalina_home }}/bin/setenv.sh"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: "0644"
    force: true
  notify: Restart tomcat

- name: Copy Tomcat server config file
  ansible.builtin.template:
    src: server.xml.j2
    dest: "{{ tomcat_server_config_file }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: "0644"
    force: true
  notify: Restart tomcat

- name: Noop to restart tomcat
  tags: restart
  block:
    - name: Trigger restart tomcat
      ansible.builtin.debug:
        msg: "trigger restart tomcat"
      notify: restart tomcat
      changed_when: false
    - name: Force handler to run now
      ansible.builtin.meta: flush_handlers
