---
- name: Prepare - install sudo and Java 17
  hosts: all
  gather_facts: true
  tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Install Java 17 before the role installs Java 8
      ansible.builtin.package:
        name: java-17-openjdk-devel
        state: present
