---
- name: Prepare - install sudo and Java 11
  hosts: all
  gather_facts: true
  tasks:
    - name: Update YUM repo baseurls
      ansible.builtin.include_role:
        name: mirsg.infrastructure.provision
        tasks_from: CentOS.yml
      when:
        ansible_facts['os_family'] == "RedHat" and
        ansible_facts['distribution_major_version'] is version('7')

    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Install Java 11 before the role installs Java 8
      ansible.builtin.package:
        name: java-11-openjdk-devel
        state: present
