---
# test this scenario from the roles/tomcat directory with the command
# molecule --base-config ../../molecule_configs/centos7_base_config.yml test --scenario centos7
platforms:
  - name: tomcat9_server
    hostname: molecule.tomcat9.local
    image: ${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-centos7-ansible:latest}
    required: true
    command: ""
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - ./tomcat9-data:/storage/molecule/tomcat9
    keep_volumes: false
    groups:
      - all
      - molecule
      - centos7
      - tomcat9
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: 192.168.56.0/24
            gateway: 192.168.56.1
    networks:
      - name: molecule
        ipv4_address: 192.168.56.2

  - name: tomcat10_server
    hostname: molecule.tomcat10.local
    image: ${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-centos7-ansible:latest}
    required: true
    command: ""
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - ./tomcat10-data:/storage/molecule/tomcat10
    keep_volumes: false
    groups:
      - all
      - molecule
      - centos7
      - tomcat10
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: 192.168.56.0/24
            gateway: 192.168.56.1
    networks:
      - name: molecule
        ipv4_address: 192.168.56.3
