---
- name: Ensure docker client cert dir exists on server
  ansible.builtin.file:
    path: "{{ docker_client_certificate_directory }}"
    state: directory
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
    mode: "0700"

- name: Generate OpenSSL client private key
  community.crypto.openssl_privatekey:
    path: "{{ docker_client_certificate_directory }}/key.pem"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
    mode: "0400"

- name: Generate OpenSSL CSR for each client using private key
  community.crypto.openssl_csr:
    path: "{{ docker_client_certificate_directory }}/{{ item }}.csr"
    privatekey_path: "{{ docker_client_certificate_directory }}/key.pem"
    common_name: "{{ item }}"
  register: new_docker_client_csr_generated
  loop: "{{ docker_client_hostnames }}"

- name: Generate client certificates signed by server CA
  community.crypto.x509_certificate:
    path: "{{ docker_client_certificate_directory }}/{{ item }}.cert"
    csr_path: "{{ docker_client_certificate_directory }}/{{ item }}.csr"
    provider: ownca
    ownca_path: "{{ docker_ca_cert }}"
    ownca_privatekey_path: "{{ docker_ca_key }}"
    mode: "0400"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
  loop: "{{ docker_client_hostnames }}"

- name: Copy signed client certificates to temp dir on Ansible controller
  ansible.builtin.fetch:
    src: "{{ docker_client_certificate_directory }}/{{ item }}.cert"
    dest: "{{ docker_client_certificate_cache_directory }}/{{ item }}.cert"
    flat: true
  loop: "{{ docker_client_hostnames }}"

- name: Copy private key to temp dir on Ansible controller
  ansible.builtin.fetch:
    src: "{{ docker_client_certificate_directory }}/key.pem"
    dest: "{{ docker_client_certificate_cache_directory }}/key.pem"
    flat: true
