---
- name: Ensure docker client cert dir exists on server
  ansible.builtin.file:
    path: "{{ docker_client_certificate_directory }}"
    state: directory
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
    mode: "0700"

- name: Generate OpenSSL client private key
  community.crypto.openssl_privatekey:
    path: "{{ docker_client_certificate_directory }}/{{ client_hostname }}.pem"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"
    mode: "0400"

- name: Generate OpenSSL CSR for client using private key
  community.crypto.openssl_csr:
    path: "{{ docker_client_certificate_directory }}/{{ client_hostname }}.csr"
    privatekey_path:
      "{{ docker_client_certificate_directory }}/{{ client_hostname }}.pem"
    common_name: "{{ client_hostname }}"
  register: new_docker_client_csr_generated

- name: Generate client certificate signed by server CA
  community.crypto.x509_certificate:
    path: "{{ docker_client_certificate_directory }}/{{ client_hostname }}.cert"
    csr_path:
      "{{ docker_client_certificate_directory }}/{{ client_hostname }}.csr"
    provider: ownca
    ownca_path: "{{ docker_ca_cert }}"
    ownca_privatekey_path: "{{ docker_ca_key }}"
    mode: "0400"
    owner: "{{ docker_owner }}"
    group: "{{ docker_group }}"

- name: Copy signed client certificate to temp dir on Ansible controller
  ansible.builtin.fetch:
    src: "{{ docker_client_certificate_directory }}/{{ client_hostname }}.cert"
    dest:
      "{{ docker_client_certificate_cache_directory }}/{{ client_hostname
      }}.cert"
    flat: true

- name: Copy private key to temp dir on Ansible controller
  ansible.builtin.fetch:
    src: "{{ docker_client_certificate_directory }}/{{ client_hostname }}.pem"
    dest:
      "{{ docker_client_certificate_cache_directory }}/{{ client_hostname }}.pem"
    flat: true
