---
- name: Get root password update command # noqa: no-changed-when
  become: true
  become_user: "{{ omero_user_system }}"
  ansible.builtin.command: >
    {{ omero_user_bin_omero }} db password --user-id 0 {{
    omero_user_reset_root_password | quote }}
  register: _omero_user_rootpwdupdate
  no_log: true

- name: Force reset omero root password # noqa: no-changed-when
  ansible.builtin.command: >
    psql -h {{ omero_user_dbhost }} -U {{ omero_user_dbuser }} -d {{
    omero_user_dbname }} -w -c {{ _omero_user_rootpwdupdate.stdout | quote }}
  environment:
    PGPASSWORD: "{{ omero_user_dbpassword }}"
  when: _omero_user_rootpwdupdate is changed
  no_log: true
