---
- name: Get password update command # noqa: no-changed-when
  become: true
  become_user: "{{ omero_user_system }}"
  ansible.builtin.command: >
    {{ omero_user_bin_omero }} db password --user-id {{ (omero_user_list |
       selectattr('login', 'equalto', item.login) | first).id }}
    {{ item.password | quote }}
  when: >
    ((omero_user_list | selectattr('login', 'equalto', item.login) |
      list | length ) > 0) and
    (item.force | default(False))
  loop: "{{ omero_user_create }}"
  loop_control:
    label: "{{ item.login }}"
  register: _omero_user_pwdupdate
  no_log: true

- name: Force reset omero password # noqa: no-changed-when
  ansible.builtin.command: >
    psql -h {{ omero_user_dbhost }} -U {{ omero_user_dbuser }} -d {{
    omero_user_dbname }} -w -c {{ item.stdout | quote }}
  when: item is changed
  loop: "{{ _omero_user_pwdupdate.results }}"
  loop_control:
    label: "{{ item.item.login }}"
  environment:
    PGPASSWORD: "{{ omero_user_dbpassword }}"
  no_log: true
