---
- name: Set up monitoring server
  hosts: monitoring_server
  become: true
  gather_facts: true

  roles:
    # - role: mirsg.infrastructure.provision
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.docker
    - role: mirsg.infrastructure.monitoring_server

- name: Set up monitoring clients
  hosts: monitoring_client
  become: true
  gather_facts: true

  roles:
    - role: mirsg.infrastructure.monitoring_client
