---
- name: Configure the XNAT web server and create PostgreSQL client certificate
  hosts: xnat
  become: true
  gather_facts: true

  roles:
    - role: mirsg.infrastructure.provision
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.install_java
    - role: mirsg.infrastructure.tomcat
    - role: mirsg.infrastructure.nginx
    - role: mirsg.infrastructure.ssl_certificates
      vars:
        ssl_certificate: "{{ postgresql_client_ssl_certificate }}" # noqa: var-naming[no-role-prefix]
      when: postgresql_use_ssl

- name: Set up XNAT database server
  hosts: db
  become: true
  gather_facts: true

  roles:
    - role: mirsg.infrastructure.provision
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.postgresql
    - role: mirsg.infrastructure.firewalld

- name: Install XNAT
  hosts: xnat
  become: true
  gather_facts: true

  roles:
    - role: mirsg.infrastructure.xnat
    - role: mirsg.infrastructure.firewalld
