---
- name: Create user accounts on all servers
  hosts: "{{ target | default('all') }}"
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  gather_facts: true

  roles:
    - role: provision_accounts
