---
# handlers file for postgresql
- name: Restart postgresql
  tags: restart
  ansible.builtin.service:
    name: "{{ postgresql_service.name }}"
    state: restarted

- name: Restore selinux contexts
  ansible.builtin.command: restorecon -R -v {{ postgresql.base_directory }}
  register: restore_selinux_contexts
  changed_when:
    - "'restorecon reset' in restore_selinux_contexts.stdout"
