---
name: Add issue to project

# yamllint disable-line rule:truthy
on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@270d5d2c3a93f1e30394f9dfdd1f53298de8e2cd # v0.85.0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-pem: ${{ secrets.APP_PEM }}
