---
name: Add issue to project

# yamllint disable-line rule:truthy
on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@37270c9d4ceb7872329515476c78654cdb5b6a83 # v0.38.0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-pem: ${{ secrets.APP_PEM }}
