---
name: Add issue to project

# yamllint disable-line rule:truthy
on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@561536e2ee67e89d148c1c9830c9debcf3a7ff07 # v0.69.0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-pem: ${{ secrets.APP_PEM }}
