---
name: links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check links
        uses: UCL-MIRSG/.github/actions/links@4bfd020ba434607bb74744ad869cd9f7c13c3a34 # v0
        with:
          app-id: ${{ vars.LINKS_APP_ID }}
          app-pem: ${{ secrets.LINKS_PRIVATE_KEY }}
