---
name: links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check links
        uses: UCL-MIRSG/.github/actions/links@058474bb0eeb6f67f8f33672d9dcbdfcb44b6584 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
