---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@5b1d34fdb29f3e4eb70c80d82f3fa952af8ee04b # v0
        with:
          ansible-roles-config: ./meta/requirements.yml
          pre-commit-config: ./.pre-commit-config.yaml
