---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install EL7 requirements
        run: |-
          ansible-galaxy install -r ./meta/el7-requirements.yml

      - name: Install EL9 requirements
        run: |-
          ansible-galaxy install -r ./meta/el9-requirements.yml

      - name: Install OMERO EL8 requirements
        run: |-
          ansible-galaxy install -r ./meta/omero-el8-requirements.yml

      - name: Install OMERO EL9 requirements
        run: |-
          ansible-galaxy install -r ./meta/omero-el9-requirements.yml

      - uses: UCL-MIRSG/.github/actions/linting@f0317ea26124fe0b3b923d881ac956301a11ea56 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
