---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@852ef0bfb5a2f1d32995b6d8e96a17eb14976527 # v0
        with:
          ansible-roles-config: ./meta/requirements.yml
          pre-commit-config: ./.pre-commit-config.yaml
