---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@3f83df9bc80b02d1e41e046e04211cc800d01980 # v0
        with:
          ansible-roles-config: ./meta/requirements.yml
          pre-commit-config: ./.pre-commit-config.yaml
