---
name: Test Python

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - molecule_configs/*
      - roles/install_python/**
      - .github/workflows/molecule.yml
      - .github/workflows/molecule-python.yml

jobs:
  molecule-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        scenario:
          - centos7
          - rocky9
    env:
      MOLECULE_RUN_TAGS: all
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - uses: UCL-MIRSG/.github/actions/molecule-test@270d5d2c3a93f1e30394f9dfdd1f53298de8e2cd # v0.85.0
        with:
          scenario: ${{ matrix.scenario }}
          base_config:
            ${{ format('{0}{1}_base_config.yml', '../../molecule_configs/',
            matrix.scenario ) }}
          checkout_path: ansible_collections/mirsg/infrastructure
          tests_path: ansible_collections/mirsg/infrastructure/roles/install_python
