---
name: Test Python

on:
  pull_request:
    paths:
      - molecule_configs/*
      - playbooks/**
      - roles/**
      - .github/workflows/molecule-python.yaml
      - "!**/README.md"

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  molecule-python:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        scenario:
          - centos7
          - rocky9
    env:
      MOLECULE_RUN_TAGS: all
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - uses: UCL-MIRSG/.github/actions/molecule-test@e16932bcb9189707188ea268d4605e042c2b5d9a # v0
        with:
          ansible_major_version: ${{ vars.ANSIBLE_MAJOR_VERSION }}
          scenario: ${{ matrix.scenario }}
          base_config:
            ${{ format('{0}{1}_base_config.yml', '../../molecule_configs/',
            matrix.scenario ) }}
          checkout_path: ansible_collections/mirsg/infrastructure
          tests_path: ansible_collections/mirsg/infrastructure/roles/install_python
