name: Test PostgreSQL
on:
  pull_request:
    paths:
      - "roles/postgresql/**"
      - "**/molecule.yml"
      - ".github/workflows/molecule-postgresql.yml"

jobs:
  molecule-postgresql:
    uses: ./.github/workflows/molecule.yml
    with:
      run-tags: provision, postgresql
