name: Test PostgreSQL
on:
  pull_request:
    paths:
      - "molecule_configs/*"
      - "roles/postgresql/**"
      - ".github/workflows/molecule.yml"
      - ".github/workflows/molecule-postgresql.yml"

jobs:
  molecule-postgresql:
    uses: ./.github/workflows/molecule.yml
    with:
      tests-path: ansible_collections/mirsg/infrastructure/roles/postgresql
