---
name: Test firewalld

on:
  pull_request:
    paths:
      - molecule_configs/*
      - playbooks/**
      - roles/**
      - .github/workflows/molecule-firewalld.yaml
      - "!**/README.md"

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  molecule-firewalld:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        scenario:
          - centos7
          - rocky9
    env:
      MOLECULE_RUN_TAGS: all
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - name:
          Edit apparmor profile for unix-chkpwd (see
          https://github.com/docker/build-push-action/issues/1302#issuecomment-3084652148)
        if: matrix.scenario == 'rocky9'
        run: |-
          sudo sed -i \
            's/capability audit_write,$/&\n  # fix: read shadow permissions (linux-pam#686)\n  capability dac_read_search,/' \
            /etc/apparmor.d/unix-chkpwd
          sudo apparmor_parser -r /etc/apparmor.d/unix-chkpwd

      - uses: UCL-MIRSG/.github/actions/molecule-test@4bfd020ba434607bb74744ad869cd9f7c13c3a34 # v0
        with:
          ansible_major_version: ${{ vars.ANSIBLE_MAJOR_VERSION }}
          scenario: ${{ matrix.scenario }}
          base_config:
            ${{ format('{0}{1}_base_config.yml', '../../molecule_configs/',
            matrix.scenario ) }}
          checkout_path: ansible_collections/mirsg/infrastructure
          tests_path: ansible_collections/mirsg/infrastructure/roles/firewalld
