name: Test Python
on:
  pull_request:
    paths:
      - "molecule_configs/*"
      - "roles/install_python/**"
      - ".github/workflows/molecule.yml"
      - ".github/workflows/molecule-python.yml"

jobs:
  molecule-firewalld:
    uses: ./.github/workflows/molecule.yml
    with:
      tests-path: ansible_collections/mirsg/infrastructure/roles/install_python
